// AUTO-GENERATED by scraper/ingest.mjs — do not edit by hand.
// Source: this group's own Facebook posts, self-hosted under images/.
window.GALLERY = [
  {
    "f": "images/hp-032.jpg",
    "c": "pets",
    "cap": "Colourful aquarium fish stones — give your tank a splash of colour. Eight colours in store."
  },
  {
    "f": "images/hp-033.jpg",
    "c": "accessories",
    "cap": "Fluorescent marine aquarium decorations and clownfish designs."
  },
  {
    "f": "images/hp-034.jpg",
    "c": "accessories",
    "cap": "Mini scissor litter scoops — scooping made easy."
  },
  {
    "f": "images/hp-035.jpg",
    "c": "accessories",
    "cap": "Plastic litter scoops for a clean, fresh pet space."
  },
  {
    "f": "images/hp-036.jpg",
    "c": "food",
    "cap": "Montego goodies in stock — Bags O' Wags and Paw Patrol dog treats."
  },
  {
    "f": "images/hp-037.jpg",
    "c": "food",
    "cap": "Montego Paw Patrol 2-in-1 dog shampoo, 250ml."
  },
  {
    "f": "images/hp-038.jpg",
    "c": "food",
    "cap": "Montego dog treats — spoil your pup with fan favourites."
  },
  {
    "f": "images/hp-039.jpg",
    "c": "store",
    "cap": "Nutrimed pet supplements — premium care, currently half price."
  },
  {
    "f": "images/hp-040.jpg",
    "c": "accessories",
    "cap": "Pet cooling mat bedding — keeps pets cool on hot days, no water or electricity. Sizes M, L, XL."
  },
  {
    "f": "images/hp-041.jpg",
    "c": "accessories",
    "cap": "Hooded cat litter box — private, odour-controlled design."
  },
  {
    "f": "images/hp-042.jpg",
    "c": "store",
    "cap": "Cat climbing stands and scratchers for natural climbing instincts."
  },
  {
    "f": "images/hp-043.jpg",
    "c": "store",
    "cap": "Metal cages, perches and feeders for parakeets, canaries and lovebirds."
  },
  {
    "f": "images/hp-044.jpg",
    "c": "store",
    "cap": "Dual cages, plastic trays and stainless-steel bowls for birds."
  },
  {
    "f": "images/hp-045.jpg",
    "c": "pets",
    "cap": "Bird nests, feeders and toys in store."
  },
  {
    "f": "images/hp-046.jpg",
    "c": "pets",
    "cap": "A big range of high-quality bird cages and accessories."
  },
  {
    "f": "images/hp-047.jpg",
    "c": "pets",
    "cap": "Reptile essentials for bearded dragons, geckos and snakes."
  },
  {
    "f": "images/hp-048.jpg",
    "c": "store",
    "cap": "Natural hides and desert-themed terrarium accessories."
  },
  {
    "f": "images/hp-049.jpg",
    "c": "food",
    "cap": "Reptile feeding bowls, small to XL."
  },
  {
    "f": "images/hp-050.jpg",
    "c": "pets",
    "cap": "Terrarium accessories for a happy, healthy reptile."
  },
  {
    "f": "images/hp-051.jpg",
    "c": "food",
    "cap": "Weekly live feed — crickets, mealworms and superworms for reptiles and birds."
  },
  {
    "f": "images/hp-052.jpg",
    "c": "store",
    "cap": "Some of the friendly faces at Heavenly Pets Petshop."
  }
];
